---
- name: Update all packages
  yum: name=* state=latest
  when: ansible_distribution_major_version == "6"

- name: Install Vindaloo
  yum: pkg=vindaloo state=latest

- name: Configure Vindaloo
  template: src=vindaloo.json.j2 dest=/opt/vindaloo/etc/vindaloo.json
  notify: Restart vindaloo

- name: Install startup script
  file: src=/opt/vindaloo/bin/vindaloo-ctl dest=/etc/init.d/vindaloo state=link
  notify: Start vindaloo
