---
- name: install gpg tools 
  yum: pkg=pygpgme state=latest

- name: install repo 
  template: src=vindaloo.repo.j2 dest=/etc/yum.repos.d/vindaloo.repo

- name: install package
  yum: pkg=vindaloo state=latest

- name: configure package
  template: src=vindaloo.json.j2 dest=/opt/vindaloo/etc/vindaloo.json

