---
#- name: Clean repo cache
#  shell: yum clean all

- name: Update Vindalu repo yum cache
  shell: yum -q makecache -y --disablerepo='*' --enablerepo='vindalu'

- name: Install Vindalu UI
  yum: pkg=vindalu-ui state=latest

- name: Install Vindalu
  yum: pkg=vindalu state=latest
  notify: Restart vindalu

- name: Remove nginx vindaloo config.
  shell: "rm -f /etc/nginx/conf.d/vindaloo.conf"
  notify: restart nginx

- name: Disable default nginx config (if present)
  shell: "if [ -f /etc/nginx/conf.d/default.conf ]; then mv /etc/nginx/conf.d/default.conf{,.disabled}; fi"
  notify: restart nginx

- name: Install startup script
  file: src=/opt/vindalu/bin/vindalu-ctl dest=/etc/init.d/vindalu state=link
  notify: Start vindalu

- name: Configure Vindalu
  template: src=vindalu.json.j2 dest=/opt/vindalu/etc/vindalu.json
  notify: Restart vindalu

- name: Configure Vindalu local admins
  template: src=local-groups.json.j2 dest=/opt/vindalu/etc/local-groups.json
  notify: Restart vindalu