---
#- name: Clean repo cache
#  shell: yum clean all
  
- name: Install Vindalu UI
  yum: pkg=vindalu-ui state=latest
  
- name: Install Vindalu
  yum: pkg=vindaloo state=latest
  notify: Restart vindaloo

- name: Disable default nginx config
  shell: "if [ -f /etc/nginx/conf.d/default.conf ]; then mv /etc/nginx/conf.d/default.conf{,.disabled}; fi"
  notify: restart nginx

- name: Install startup script
  file: src=/opt/vindaloo/bin/vindaloo-ctl dest=/etc/init.d/vindaloo state=link
  notify: Start vindaloo

- name: Configure Vindalu
  template: src=vindaloo.json.j2 dest=/opt/vindaloo/etc/vindaloo.json
  notify: Restart vindaloo
  
- name: Configure Vindalu local admins
  template: src=local-groups.json.j2 dest=/opt/vindaloo/etc/local-groups.json
  notify: Restart vindaloo